### ISSUE TITLE
Option to handle other things than scripts

### ISSUE THREAD

**Issue by petero-dk** [BerserkerDotNet/CaptureRenderTagHelper#3]
This is such an elegant way of handling this that I extended the code to accept any tag type and changed the name.

Are you interested in an upstream PR or should the fork live its own life? I ask because this would be a major breaking change (in the way that I did it), obviously it does not need to be a breaking change if you are willing to accept the naming would not showcase the full potential.

(My fork: https://github.com/zealofzebras/SectionCaptureTagHelper)

**Comment by BerserkerDotNet** [comment]
@petero-dk, sorry, I somehow missed the notification about your message.

It is an interesting idea, I never thought about it that way, can you elaborate more on when and how it will be useful to capture other html tags, please? Some example would help a lot.

**Comment by petero-dk** [comment]
One use case that we use it for is to dynamically change the header of a given page (one could argue that this could be achieved through normal sections or changing the layout page.

In order to maintain a pretty header image we need it to be in the same div as the main nav. However this is separated from the `@RenderBody` because of this we need sections. Using this plugin we can use another method I added called (Html.IfCaptured) to set the css class based on the presence of the capture group.

One additional issue is that some of our pages are partial views because of nesting and obviously normal sections does not work there.

An example would be:

We have a layout page where
```razor
<body class="@Html.IfCaptured("herorow", " hero")">
    <header id="hero">
        <nav class="navbar navbar-expand-sm fixed-top navbar-toggleable-sm navbar-dark mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">Domains</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Demo">Redirects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <section render="herorow" />
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
```

With the page specifying the following:

```razor
<section capture="herorow" nooutputtag="true">
    <div class="container py-5">
        <div class="row herorow">
            <div class="info text-light">
                <h2>Info</h2>
            </div>
            <div class="figure text-center">
                <img src="~/img/hero-image.png" alt="hero-image" class="hero-image">
            </div>
        </div>
    </div>
</section>
```

This can be seen at:
This page where the header is set: https://rere.direct/ 
This page where the header is not set: https://rere.direct/Article/Why%20You%20Should%20Have%20More%20Domains

**Comment by BerserkerDotNet** [comment]
@petero-dk, thank you for a detailed explanation. I see how it might be useful to capture other tags besides `script`. 
It will be some effort to make it work correctly with other tags.

What I think needs to be done:
1. It should capture any tags (not only sections or scripts)
2. Everything should be renamed to `ElementCaptureTagHelper` ( `ElementRenderTagHelper`) ( I would love to hear if you have a suggestion for a better name :) )
3. All existing features should work with other tags. (Multiple blocks capture, order, merge, and de-duplication). For de-duplication, it no longer makes sense to compare by `src`, probably you'll need to check if it is a script element or not and chose the appropriate attribute. (`src` for a script and `id` for other tags)
4. Update/Write new tests
5. Update docs and examples

If you're okay with spending time getting a PR ready and addressing possible comments, I'll be glad to accept it. If you think it is too much effort, that's okay too, just let me know :)

**Comment by rclabo** [comment]
It is cool to use it with other tags.  In my case I tweaked the source to use it with style tags in additions to script tags.  That way I can define "components" in a file and include the related scripts and styles in the component and know that those styles and scripts will get merged into the page in the right locations at render time.  Since I was making the change to solve a specific need I had I didn't do it in a way that honored all the other features of the tag helper (merge for example) but I can attest that having support for other tags (like in my case style) can be really useful.

**Comment by petero-dk** [comment]
@BerserkerDotNet 

I am a little pressed for time right now, but when I get around to it I can easily fix 1, 2, and 3. I will spend a day thinking about naming and get back with a comment here if I come up with a brilliant idea. Otherwise I think your suggestion is quite good it is similar enough for current users to feel familiar.

**Comment by petero-dk** [comment]
I actually think I might have renamed some of it to ContentCaptureTagHelper which I thought would focus on the fact that it captures the content. What do you think about that?

**Comment by petero-dk** [comment]
Which actually goes to show I should check what I have actually submitted. The code I have in this PR is called ContentCaptureTagHelper and it works on all elements not just section or script. Wow, I must not really have been awake when I did this. But all checks out, I have just added a check for id comparison along with src. Will spend a few more seconds to think about it. I just need a final decision on the naming.

**Comment by rclabo** [comment]
Another name to consider is CaptureRenderTagHelper since these are the two attributes that it adds to tags and the premise by which it works.

**Comment by BerserkerDotNet** [comment]
@petero-dk, I saw that you renamed it to ContentCaptureTagHelper, but it just does not sound right to me. `Content` sounds too vague. I actually like @rclabo suggestion, it reflects what the library does very clearly and does not tie it to a specific thing, like content, element, or script. Let's use `CaptureRenderTagHelper` as a new name.

**Comment by petero-dk** [comment]
There you go #4 that has a namechange and implemented 1,2,3. Notice the noduplicatesource detection can now be any arbitrary attribute. If the property is set to "true" it will check for duplication on both src and id, otherwise it will check for attributes with the name of the value. 

By default it only checks for "src" attributes as that was the previous behaviour. This could be changed to "true"

See this source:
https://github.com/zealofzebras/SectionCaptureTagHelper/blob/c6a97a3bdd5f92ada3abf2b9873a75a812feb857/CaptureRenderTagHelper/RenderTagHelper.cs#L34-L38

**Comment by petero-dk** [comment]
Closing because of PR #4

**Comment by BerserkerDotNet** [comment]
Official NuGet for [CaptureRenderTagHelper](https://www.nuget.org/packages/CaptureRenderTagHelper/ ) is published.

CC: @petero-dk @rclabo

**Comment by rclabo** [comment]
Sweet, I'll try to switch to using it next week instead of my modified fork.
